favicon: /avatar.png
avatar: /avatar.png
katex: true
force_https: true
check_update: true

menus:
  - name: 首页
    link: /
  - name: 归档
    link: /archives/
  - name: 标签
    link: /tags/
  - name: 其它
    link: /code/
post:
  feature: true
disqus:
  enable: false
  shortname: 'Your shortname here'
  api: 'Your api here'
  apikey: 'Your api key here'
  admin: 'Your disqus username here'
gitalk:
  enable: false
  clientId: 'Your Client Id here'
  clientSecret: 'Your Client Secret here'
  repository: 'Your Comment Repository here'
  owner: 'Your github username here'
web_analytics:
  enable: false
  google: UA-12345678-1
  baidu: 12345678
footer: |
  Footer HTML
